import turtle
turtle.Screen().bgcolor("Aqua")
board=turtle.Turtle()
board.forward(100)
board.left(90)
board.forward(100)
board.left(90)
board.forward(100)
board.left(90)
board.forward(100)
board.left(90)